language: java
before_install: 
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: C/c3WoJopFHFmNMacp1Z9AXt4n50/+zvlsdu9vms9LVUw+teLKtWSAZ094T1TRBJnt6yA4HkfteBP6B+ip3XfScSgpDc1Lk0DKFvUyDLv2aHYpT1JoYi5FNa1xHG4REdxOBdXinYMswMCYZJkvPaT4tSKsANYXwYEEHkAY3VfGY=
